## Numpy Array

In [1]:
import numpy as np

In [12]:
a=[1,0,5]
b=[3,4,6]
c=[5,10,-8]

In [14]:
num_arr=np.array([a,b,c]) #convert list into numpy array
print(num_arr)

[[ 1  0  5]
 [ 3  4  6]
 [ 5 10 -8]]


### Shape and Reshape

In [18]:
num_arr.shape   #gives the dimension of numpy array

(3, 3)

In [20]:
#num_arr.shape=(3,2) #to reshape the array size in case of variable array

In [23]:
#np.reshape(num_arr,(3,2))   #to reshape the array size in case of variable array

### Transpose and Flatten

In [24]:
np.transpose(num_arr)  

array([[ 1,  3,  5],
       [ 0,  4, 10],
       [ 5,  6, -8]])

In [27]:
x=num_arr.flatten() #flattens the array to one dimension
print(x)

[ 1  0  5  3  4  6  5 10 -8]


### Concatenate

In [28]:
num_arr2=np.array([[1,2,3],
                  [2,3,5],
                  [6,7,8]])

In [32]:
np.concatenate((num_arr,num_arr2),axis=1)   #axis=1 means horizontal concatenation

array([[ 1,  0,  5,  1,  2,  3],
       [ 3,  4,  6,  2,  3,  5],
       [ 5, 10, -8,  6,  7,  8]])

### Zeros And Ones

In [34]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Identity and Eye

In [40]:
np.identity(3,dtype=int)  #3 means 3*3 matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.eye(3,3,k=0,dtype=int)   #main diagonal 1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
np.eye(3,3,k=1,dtype=int)   # first upper diagonal from main diagonal 1

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [47]:
np.eye(3,3,k=2,dtype=int)   # second upper diagonal from main diagonal 1

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
np.eye(3,3,k=-1,dtype=int)   # first lower diagonal from main diagonal 1

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

### Array Mathematics

In [53]:
num_arr+num_arr2   #or 
np.add(num_arr,num_arr2)

array([[ 2,  2,  8],
       [ 5,  7, 11],
       [11, 17,  0]])

In [56]:
# a-b or np.add(a,-b)
# a*b or np.multiply(a,b)
# a/b or np.divide(a,b)
# a%b or np.mod(a,b)
# a**b or np.power(a,b)

### floor , ceil, rint

In [61]:
np.floor(num_arr)
np.ceil(num_arr)
np.rint(num_arr)   #round upto nearest integer

array([[ 1.,  0.,  5.],
       [ 3.,  4.,  6.],
       [ 5., 10., -8.]])

## ways of formatting the elements (set_printoptions)

In [63]:
np.set_printoptions(precision=2)
np.array([100.5467656])

array([100.55])

In [66]:
np.set_printoptions(sign=' ')   #add somthing in between the elements (in this case space)
np.array([1,2,3])

array([1, 2, 3])

In [67]:
##see docs for more

### Sum and Prod

In [71]:
a=np.array([[1,2],    
           [3,4]])
np.sum(a,axis=0)   #sum of column 1 and 3, 2 and 4

array([4, 6])

In [72]:
np.sum(a,axis=1)

array([3, 7])

In [74]:
np.sum(a,axis=None)   #sum of all

10

In [75]:
#same but in place of sum prod