In [1]:
import numpy as np

## POLYNOMIALS

In [6]:
np.poly([2,3])   #list is the roots of the polynomial and it return the coefficient of polyomial

array([ 1., -5.,  6.])

In [8]:
np.roots([1,-5,6])  #returns the roots of the polymial with coefficients as in the list

array([3., 2.])

In [10]:
np.polyint([1,-5,6])  #returns the antiderivate

array([ 0.33333333, -2.5       ,  6.        ,  0.        ])

In [12]:
np.polyder([1,-5,6])  #returns the derivative

array([ 2, -5])

In [14]:
np.polyval([1,-5,6],1) #returns the value of the polynomial with value of variable as 1

2

In [35]:
a=np.array([1,2])
b=np.array([5,0])

np.polyfit(a,b,1)   #fits the curve

array([-5., 10.])

## Linear Algebra

In [36]:
a=np.array([[1,2],    
           [3,4]])
np.linalg.det(a)   #determinant

-2.0000000000000004

In [26]:
np.linalg.inv(a)   #inverse of matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
vals,vecs =np.linalg.eig(a)
print(vals)    #eigen value
print(vecs)    #eigen vector

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
